### ISSUE TITLE
Don't tag include_tasks 

### ISSUE THREAD

**Issue by machacekondra** [oVirt/ovirt-ansible-disaster-recovery#13]
Since Ansible 2.5 tags of `include_tasks` task, won't be resolved:

 https://github.com/ansible/ansible/issues/35183#issuecomment-359461271

Please change `include_tasks` to `import_tasks`.

@maorlipchuk

**Comment by maorlipchuk** [comment]
Waiting for a documentation update how to port include_tasks to import_tasks with loops #35096
see also https://groups.google.com/forum/#!searchin/ansible-project/chipcha%7Csort:date/ansible-project/yQZOpOiXDuM/Cs5_f-3sAQAJ

**Comment by maorlipchuk** [comment]
Fixed in https://github.com/oVirt/ovirt-ansible-disaster-recovery/pull/42
