### ISSUE TITLE
Separate roles for preparation, failover and failback

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-ansible-disaster-recovery#17]
The use of tags is not intuitive and is not going to be very user friendly, especially during crisis.
Using separate roles would simplify usage for the users.

**Comment by maorlipchuk** [comment]
For now I will introduce a shell script as part of the role which should make it much more intuitive for the user to apply fail-over and fail-back with default values.

**Comment by maorlipchuk** [comment]
Related fix in https://github.com/oVirt/ovirt-ansible-disaster-recovery/pull/38

**Comment by maorlipchuk** [comment]
Introduced the ovirt-dr script to provide the user a more convinient way to run disaster recovery actions as a way to avoid using ansible playbooks directly.

ovirt-dr should support several actions which the user can execute:

1) validate	validate the var file mapping which is used for failover and failback
2) generate	Generate the mapping var file based on the primary and secondary setup, to be used for failover and failback
3) failover	Start a failover process to the target setup
4) failback	Start a failback process from the target setup to the source setup
Each of those actions is using a configuration file which its default location is files/dr.conf

Here are few examples how the script can be run:
For mapping file generation:
./ovirt-dr generate
For mapping file validation:
./ovirt-dr validate
For fail-over operation:
./ovirt-dr failover
For fail-back operation:
./ovirt-dr failback

Basic functionality of validation is working well, proper bugs will be opened to map the gaps which were left to solve.
