### ISSUE TITLE
Failover does not map any LUN disks to any VM in RHVM

### ISSUE THREAD

**Issue by tonyppe** [oVirt/ovirt-ansible-disaster-recovery#78]
Initiating a failover does not trigger any action to add the LUN disk to RHVM (issue 77) but in addition, there is no process to later add this lun disk to the associated VM. The mapping file contains the lun disks. The host logs into the lun. But the failover completes without adding the lun disk into the respected VM. 

The result is, the VMs dont have any disks added and therefore fail to boot later in the playbook execution process. 
 
Linked to issue 77 (RHVM does not contain any LUN disks) as we first need the lun disks added to RHVM so that there are lun disks to add to the VM itself for booting. 

Critical blocker - ovirt-ansible-disaster-recovery does not work.

**Comment by shenitzky** [comment]
Hi, Can you please submit a bug using bugzilla if it is still relevant?
https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine

This repository is now in read-only mode.

**Comment by tonyppe** [comment]
Hi, it is still relevant unless fixed. Can you confirm fixed? Else
please do the needful.

Regards,
Tony Pearce

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
